name: kidlogame_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.0.0
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  flutter_login: ^4.1.1
  shared_preferences: ^2.1.2
  crypto: ^3.0.3
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
