name: kidlogame_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.0.0
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  flutter_login: ^4.1.1
  shared_preferences: ^2.1.2
  crypto: ^3.0.3
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4
  animated_splash_screen: ^1.3.0
  flutter_animator: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/graphics/loginScreen1.png
    - assets/images/icons/google.png
    - assets/images/icons/

  fonts:
    - family: Balsamiq_Sans
      fonts:
        - asset: assets/fonts/Balsamiq_Sans/BalsamiqSans-Regular.ttf
          weight: 700

    - family: Bebas_Neue
      fonts:
        - asset: assets/fonts/Bebas_Neue/BebasNeue-Regular.ttf

    - family: Bubblegum_Sans
      fonts:
        - asset: assets/fonts/Bubblegum_Sans/BubblegumSans-Regular.ttf

    - family: Comic_Neue
      fonts:
        - asset: assets/fonts/Comic_Neue/ComicNeue-Regular.ttf
        - asset: assets/fonts/Comic_Neue/ComicNeue-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comic_Neue/ComicNeue-Light.ttf
          weight: 300

    - family: Dancing_Script
      fonts:
        - asset: assets/fonts/Dancing_Script/DancingScript-VariableFont_wght.ttf

    - family: Handlee
      fonts:
        - asset: assets/fonts/Handlee/Handlee-Regular.ttf

    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster/Lobster-Regular.ttf

    - family: Montserrat_Alternates
      fonts:
        - asset: assets/fonts/Montserrat Alternates/MontserratAlternates-Regular.ttf
        - asset: assets/fonts/Montserrat Alternates/MontserratAlternates-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat Alternates/MontserratAlternates-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat Alternates/MontserratAlternates-Medium.ttf
          weight: 500

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/Nunito/Nunito-VariableFont_wght.ttf


    - family: Patrick_Hand
      fonts:
        - asset: assets/fonts/Patrick_Hand/PatrickHand-Regular.ttf

    - family: Patrick_Hand_SC
      fonts:
        - asset: assets/fonts/Patrick_Hand_SC/PatrickHandSC-Regular.ttf


    - family: Titillium_Web
      fonts:
        - asset: assets/fonts/Titillium_Web/TitilliumWeb-Black.ttf

    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500