name: kidlogame_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.0.0
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  flutter_login: ^4.1.1
  shared_preferences: ^2.1.2
  crypto: ^3.0.3
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4
  animated_splash_screen: ^1.3.0
  flutter_animator: ^3.2.2
  intl: ^0.18.1
  textfield_tags: ^2.0.2
  flutter_chips_input: ^2.0.0
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/graphics/
    - assets/images/icons/
    - assets/images/subjects/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500